[{"id":0,"fix":""},
{"id":1,"fix":""},
{"id":2,"fix":"Johnny Coles"},
{"id":3,"fix":""},
{"id":4,"fix":""},
{"id":5,"fix":""},
{"id":6,"fix":""},
{"id":7,"fix":"Irving Kahl"},
{"id":8,"fix":""},
{"id":9,"fix":""},
{"id":10,"fix":"Jack Stick"},
{"id":11,"fix":""},
{"id":12,"fix":""},
{"id":13,"fix":""},
{"id":14,"fix":""},
{"id":15,"fix":"Wayne Shorter"},
{"id":16,"fix":""},
{"id":17,"fix":""},
{"id":18,"fix":""},
{"id":19,"fix":""},
{"id":20,"fix":""},
{"id":21,"fix":""},
{"id":22,"fix":"Lee Morgan"},
{"id":23,"fix":""},
{"id":24,"fix":""},
{"id":25,"fix":""},
{"id":26,"fix":""},
{"id":27,"fix":""},
{"id":27,"fix":""},
{"id":28,"fix":""},
{"id":29,"fix":""},
{"id":30,"fix":""},
{"id":31,"fix":""},
{"id":32,"fix":""},
{"id":33,"fix":"George and Ira Gerschwinn"},
{"id":34,"fix":"Victor Young, Bing Crosby"},
{"id":35,"fix":"Eddie Green"},
{"id":36,"fix":""},
{"id":37,"fix":""},
{"id":38,"fix":""},
{"id":39,"fix":"Max Roach"},
{"id":40,"fix":""},
{"id":41,"fix":"Emeur Diodato"},
{"id":42,"fix":""},
{"id":43,"fix":"Charles Strouse, Lee Adams"},
{"id":44,"fix":""},
{"id":45,"fix":"Doc Pomus, shuman"},
{"id":46,"fix":"Robin, Gillespie"},
{"id":47,"fix":""},
{"id":48,"fix":""},
{"id":49,"fix":"Irving Berlin"},
{"id":50,"fix":""},
{"id":51,"fix":""},
{"id":52,"fix":""},
{"id":53,"fix":""},
{"id":54,"fix":""},
{"id":55,"fix":""},
{"id":56,"fix":"Bob Montgomery"},
{"id":57,"fix":""},
{"id":58,"fix":""},
{"id":59,"fix":""},
{"id":60,"fix":"Louis Prima,Barbara Belle, Anita Leonard, Stan Rhodes"},
{"id":61,"fix":""},
{"id":62,"fix":""},
{"id":63,"fix":""},
{"id":64,"fix":""},
{"id":65,"fix":"lenny tristrand"},
{"id":64,"fix":""},
{"id":65,"fix":""},
{"id":66,"fix":"charlie christian"},
{"id":67,"fix":""},
{"id":68,"fix":""},
{"id":69,"fix":"Wayne Shorter"},
{"id":70,"fix":"Enric Madriguera"},
{"id":71,"fix":""},
{"id":72,"fix":"Jose Feliciano"},
{"id":73,"fix":"Lee Morgan"},
{"id":74,"fix":"John Coltrane"},
{"id":75,"fix":""},
{"id":76,"fix":""},
{"id":77,"fix":""},
{"id":78,"fix":"Joe Henderson"},
{"id":79,"fix":"Mike Stein"},
{"id":80,"fix":"Claire Fischer"},
{"id":81,"fix":""},
{"id":82,"fix":"E.Humperdinck"},
{"id":83,"fix":""},
{"id":84,"fix":"after you"},
{"id":85,"fix":""},
{"id":86,"fix":"Kevin Eubanks"},
{"id":87,"fix":""},
{"id":88,"fix":"Lionel Newman"},
{"id":89,"fix":""},
{"id":90,"fix":"Antonio Carlos Jobim"},
{"id":91,"fix":""},
{"id":92,"fix":""},
{"id":93,"fix":""},
{"id":94,"fix":"Gerry Mulligan"},
{"id":95,"fix":""},
{"id":96,"fix":""},
{"id":97,"fix":""},
{"id":98,"fix":"Eddie Holland, Norman Whitfield"},
{"id":99,"fix":"J Heath"},
{"id":100,"fix":""},
{"id":101,"fix":"Charlie Christian, Jimmy Mundy, Benny Goodman"},
{"id":102,"fix":""},
{"id":103,"fix":"Charlie Christian"},
{"id":104,"fix":""},
{"id":105,"fix":""},
{"id":106,"fix":"Torriie Zito"},
{"id":107,"fix":""},
{"id":108,"fix":""},
{"id":109,"fix":"Kenny Werner"},
{"id":110,"fix":"Enrique Jorin"},
{"id":111,"fix":""},
{"id":112,"fix":""},
{"id":113,"fix":""},
{"id":114,"fix":"Dizzy Gilespie"},
{"id":115,"name":"ALICE IN WONDERLAND","name2":"ALL ABOUT RONNIE","fix":""},
{"id":116,"name":"ALL ABOUT RONNIE","name2":"ALL ALONE","fix":""},
{"id":117,"name":"ALL ALONE","name2":"ALL BLUES","fix":"waldren, irving berlin"},
{"id":118,"name":"ALL BLUES","name2":"ALL GOD'S CHILLUN GOT RHYTHM","fix":""},
{"id":119,"name":"ALL GOD'S CHILLUN GOT RHYTHM","name2":"ALL IN LOVE IS FAIR","fix":""},
{"id":120,"name":"ALL IN LOVE IS FAIR","name2":"ALL MEMBERS","fix":""},
{"id":121,"name":"ALL MEMBERS","name2":"ALL MY LOVING","fix":""},
{"id":122,"name":"ALL MY LOVING","name2":"ALL MY TOMORROWS","fix":"The Beatles"},
{"id":123,"name":"ALL MY TOMORROWS","name2":"ALL OF ME","fix":""},
{"id":124,"name":"ALL OF ME","name2":"ALL OF YOU","fix":"Seymore Simons, Gerald Marks"},
{"id":125,"name":"ALL OF YOU","name2":"ALL OR NOTHING AT ALL","fix":""},
{"id":126,"name":"ALL OR NOTHING AT ALL","name2":"ALL THE THINGS YOU ARE","fix":""},
{"id":127,"name":"ALL THE THINGS YOU ARE","name2":"ALL THE WAY","fix":""},
{"id":128,"name":"ALL THE WAY","name2":"ALL THROUGH THE NIGHT","fix":""},
{"id":129,"name":"ALL THROUGH THE NIGHT","name2":"ALL TOO SOON","fix":""},
{"id":130,"name":"ALL TOO SOON","name2":"ALL YOU WERE TO US","fix":""},
{"id":131,"name":"ALL YOU WERE TO US","name2":"ALLEY CAT","fix":"STEFAN KARLSON"},
{"id":132,"name":"ALLEY CAT","name2":"ALLEZ VOUS EN","fix":""},
{"id":133,"name":"ALLEZ VOUS EN","name2":"ALLVIO","fix":""},
{"id":134,"name":"ALLVIO","name2":"ALMA CON ALMA","fix":"JULIO CUBO"},
{"id":135,"name":"ALMA CON ALMA","name2":"ALMENDRA","fix":""},
{"id":136,"name":"ALMENDRA","name2":"ALMOST LIKE BEING IN LOVE","fix":""},
{"id":137,"name":"ALMOST LIKE BEING IN LOVE","name2":"ALONE TOGETHER","fix":""},
{"id":138,"name":"ALONE TOGETHER","name2":"ALONE TOO LONG","fix":""},
{"id":139,"name":"ALONE TOO LONG","name2":"ALONG CAME BETTY","fix":""},
{"id":140,"name":"ALONG CAME BETTY","name2":"ALRIGHT OKAY YOU WIN","fix":""},
{"id":141,"name":"ALRIGHT OKAY YOU WIN","name2":"ALTOITIS","fix":"SID WYCHE MAMEE WATTS *"},
{"id":142,"name":"ALTOITIS","name2":"ALWAYS AND FOREVER","fix":"OLIVER NELSON"},
{"id":143,"name":"ALWAYS AND FOREVER","name2":"ALWAYS THERE","fix":"PAT METHENY"},
{"id":144,"name":"ALWAYS THERE","name2":"ALWAYS TRUE TO MY FASHION","fix":"WAYNE SHORTER"},
{"id":145,"name":"ALWAYS TRUE TO MY FASHION","name2":"ALWAYS","fix":""},
{"id":146,"name":"ALWAYS","name2":"AM I BLUE","fix":"IRVING BERLIN"},
{"id":147,"name":"AM I BLUE","name2":"AMAPOLA","fix":""},
{"id":148,"name":"AMAPOLA","name2":"AMAZING GRACE","fix":""},
{"id":149,"name":"AMAZING GRACE","name2":"AMERICAN GOTHIC","fix":"TRADITIONAL"},
{"id":150,"name":"AMERICAN GOTHIC","name2":"AMERICAN PATROL","fix":"BOB BERG"},
{"id":151,"name":"AMERICAN PATROL","name2":"AMONG MY SOUVENIRS","fix":"GLEN MILLER"},
{"id":152,"name":"AMONG MY SOUVENIRS","name2":"AMOR ESPERAME","fix":""},
{"id":153,"name":"AMOR ESPERAME","name2":"AMOR SONADOR","fix":"MEME SOLIS"},
{"id":154,"name":"AMOR SONADOR","name2":"AN OSCAR FOR TREADWELL","fix":"JOHN STUBBLEFIELD"},
{"id":155,"name":"AN OSCAR FOR TREADWELL","name2":"ANA MARIA","fix":""},
{"id":156,"name":"ANA MARIA","name2":"ANAMARIA","fix":""},
{"id":157,"name":"ANAMARIA","name2":"AND ALL THAT JAZZ","fix":""},
{"id":158,"name":"AND ALL THAT JAZZ","name2":"AND FAR AWAY","fix":""},
{"id":159,"name":"AND FAR AWAY","name2":"AND I LOVE HER","fix":""},
{"id":160,"name":"AND I LOVE HER","name2":"AND I THINK ABOUT IT ALL THE TIME","fix":"THE BEATLES"},
{"id":161,"name":"AND I THINK ABOUT IT ALL THE TIME","name2":"AND IT ALL GOES ROUND","fix":"EARNIE WATTS, RAY DEWEY"},
{"id":162,"name":"AND IT ALL GOES ROUND","name2":"AND NOW THE QUEEN","fix":"BERNARD IHNGER*"},
{"id":163,"name":"AND NOW THE QUEEN","name2":"AND ON THE THIRD DAY","fix":""},
{"id":164,"name":"AND ON THE THIRD DAY","name2":"AND ONE MORE FOR THE ROA","fix":"MICHAEL GIBBS"},
{"id":165,"name":"AND ONE MORE FOR THE ROA","name2":"AND THE ANGELS SING","fix":""},
{"id":166,"name":"AND THE ANGELS SING","name2":"ANDALUCIA","fix":""},
{"id":167,"name":"ANDALUCIA","name2":"ANGEL EYES","fix":"ERNESTO LUCUONIA*"},
{"id":168,"name":"ANGEL EYES","name2":"ANGELA","fix":""},
{"id":169,"name":"ANGELA","name2":"ANNIVERSARY SONG","fix":"ANTONIO CARLOS JOBIM"},
{"id":170,"name":"ANNIVERSARY SONG","name2":"ANNIVERSARY WALTZ","fix":""},
{"id":171,"name":"ANNIVERSARY WALTZ","name2":"ANOTHER HAIRDO","fix":""},
{"id":172,"name":"ANOTHER HAIRDO","name2":"ANOTHER KIND OF SOUL","fix":"CHARLIE PARKER"},
{"id":173,"name":"ANOTHER KIND OF SOUL","name2":"ANOTHER STAR","fix":"NAT CANNONBALL ADERLY"},
{"id":174,"name":"ANOTHER STAR","name2":"ANOTHER TIME","fix":""},
{"id":175,"name":"ANOTHER TIME","name2":"ANTHROPOLOGY","fix":"ALAN BROADBENT"},
{"id":176,"name":"ANTHROPOLOGY","name2":"ANTI CLIMAX","fix":""},
{"id":177,"name":"ANTI CLIMAX","name2":"ANTIGUA","fix":""},
{"id":178,"name":"ANTIGUA","name2":"ANYTHING GOES","fix":"ROLAND PRINCE"},
{"id":179,"name":"ANYTHING GOES","name2":"ANYTIME","fix":""},
{"id":180,"name":"ANYTIME","name2":"APPLAUSE","fix":""},
{"id":181,"name":"APPLAUSE","name2":"APPLE CORE","fix":""},
{"id":182,"name":"APPLE CORE","name2":"APPLE HONEY","fix":""},
{"id":183,"name":"APPLE HONEY","name2":"APPOINTMENT IN GHANA","fix":""},
{"id":184,"name":"APPOINTMENT IN GHANA","name2":"APRIL HEAD","fix":""},
{"id":185,"name":"APRIL HEAD","name2":"APRIL IN PARIS","fix":"HARLEY LEONARD"},
{"id":186,"name":"APRIL IN PARIS","name2":"APRIL JOY","fix":""},
{"id":187,"name":"APRIL JOY","name2":"APRIL SHOWERS","fix":""},
{"id":188,"name":"APRIL SHOWERS","name2":"APRIL SKIDS","fix":""},
{"id":189,"name":"APRIL SKIDS","name2":"APRIL","fix":"BUDDY COLLETTE"},
{"id":190,"name":"APRIL","name2":"AQUARIUS","fix":"LENNIE TRISTANO*"},
{"id":191,"name":"AQUARIUS","name2":"AQUELLA TARDE","fix":"JOAO DONATO"},
{"id":192,"name":"AQUELLA TARDE","name2":"ARE THEY ONLY DREAMS","fix":"ERNESTO LACOUNA*"},
{"id":193,"name":"ARE THEY ONLY DREAMS","name2":"ARE YOU HAVIN' ANY FUN","fix":"WOODY SHAW"},
{"id":194,"name":"ARE YOU HAVIN' ANY FUN","name2":"AREN'T YOU GLAD YOU'RE YOU","fix":""},
{"id":195,"name":"AREN'T YOU GLAD YOU'RE YOU","name2":"ARIETAS","fix":""},
{"id":196,"name":"ARIETAS","name2":"ARISE HER EYES","fix":"FREDDIE HUBBARD"},
{"id":196,"name":"ARISE HER EYES","name2":"ARISE HER EYES","fix":""},
{"id":196,"name":"ARISE HER EYES","name2":"ARISE HER EYES","fix":""},
{"id":196,"name":"ARISE HER EYES","name2":"ARISE HER EYES","fix":""},
{"id":197,"name":"ARMAGEDDON","name2":"ARMAGEDDON","fix":"WAYNE SHORTER"},
{"id":198,"name":"ARMANDO'S RHUMBA","name2":"ARMANDO'S RHUMBA","fix":""},
{"id":199,"name":"AROUND AGAIN","name2":"AROUND AGAIN","fix":"CARLA BLEY"},
{"id":199,"name":"AROUND AGAIN","name2":"AROUND AGAIN","fix":""},
{"id":199,"name":"AROUND AGAIN","name2":"AROUND AGAIN","fix":""},
{"id":202,"name":"ARRIVING SOON","name2":"ARRIVING SOON","fix":"CHARLIE PARKER"},
{"id":204,"name":"AS CATCH CAN","name2":"AS CATCH CAN","fix":""},
{"id":206,"name":"AS LONG AS I HAVE YOU","name2":"AS LONG AS I HAVE YOU","fix":"WILLIE DIXON *"},
{"id":207,"name":"AS LONG AS I LIVE","name2":"AS LONG AS I LIVE","fix":""},
{"id":208,"name":"AS TIME GOES BY","name2":"AS TIME GOES BY","fix":""},
{"id":209,"name":"AS WE SPEAK","name2":"AS WE SPEAK","fix":"david sanborn michael sembello"},
{"id":210,"name":"ASA","name2":"ASA","fix":""},
