[{"id":0,"fix":""},
{"id":1,"fix":""},
{"id":2,"fix":"Johnny Coles"},
{"id":3,"fix":""},
{"id":4,"fix":""},
{"id":5,"fix":""},
{"id":6,"fix":""},
{"id":7,"fix":"Irving Kahl"},
{"id":8,"fix":""},
{"id":9,"fix":""},
{"id":10,"fix":"Jack Stick"},
{"id":11,"fix":""},
{"id":12,"fix":""},
{"id":13,"fix":""},
{"id":14,"fix":""},
{"id":15,"fix":"Wayne Shorter"},
{"id":16,"fix":""},
{"id":17,"fix":""},
{"id":18,"fix":""},
{"id":19,"fix":""},
{"id":20,"fix":""},
{"id":21,"fix":""},
{"id":22,"fix":"Lee Morgan"},
{"id":23,"fix":""},
{"id":24,"fix":""},
{"id":25,"fix":""},
{"id":26,"fix":""},
{"id":27,"fix":""},
{"id":27,"fix":""},
{"id":28,"fix":""},
{"id":29,"fix":""},
{"id":30,"fix":""},
{"id":31,"fix":""},
{"id":32,"fix":""},
{"id":33,"fix":"George and Ira Gerschwinn"},
{"id":34,"fix":"Victor Young, Bing Crosby"},
{"id":35,"fix":"Eddie Green"},
{"id":36,"fix":""},
{"id":37,"fix":""},
{"id":38,"fix":""},
{"id":39,"fix":"Max Roach"},
{"id":40,"fix":""},
{"id":41,"fix":"Emeur Diodato"},
{"id":42,"fix":""},
{"id":43,"fix":"Charles Strouse, Lee Adams"},
{"id":44,"fix":""},
{"id":45,"fix":"Doc Pomus, shuman"},
{"id":46,"fix":"Robin, Gillespie"},
{"id":47,"fix":""},
{"id":48,"fix":""},
{"id":49,"fix":"Irving Berlin"},
{"id":50,"fix":""},
{"id":51,"fix":""},
{"id":52,"fix":""},
{"id":53,"fix":""},
{"id":54,"fix":""},
{"id":55,"fix":""},
{"id":56,"fix":"Bob Montgomery"},
{"id":57,"fix":""},
{"id":58,"fix":""},
{"id":59,"fix":""},
{"id":60,"fix":"Louis Prima,Barbara Belle, Anita Leonard, Stan Rhodes"},
{"id":61,"fix":""},
{"id":62,"fix":""},
{"id":63,"fix":""},
{"id":64,"fix":""},
{"id":65,"fix":"lenny tristrand"},
{"id":64,"fix":""},
{"id":65,"fix":""},
{"id":66,"fix":"charlie christian"},
{"id":67,"fix":""},
{"id":68,"fix":""},
{"id":69,"fix":"Wayne Shorter"},
{"id":70,"fix":"Enric Madriguera"},
{"id":71,"fix":""},
{"id":72,"fix":"Jose Feliciano"},
{"id":73,"fix":"Lee Morgan"},
{"id":74,"fix":"John Coltrane"},
{"id":75,"fix":""},
{"id":76,"fix":""},
{"id":77,"fix":""},
{"id":78,"fix":"Joe Henderson"},
{"id":79,"fix":"Mike Stein"},
{"id":80,"fix":"Claire Fischer"},
{"id":81,"fix":""},
{"id":82,"fix":"E.Humperdinck"},
{"id":83,"fix":""},
{"id":84,"fix":"after you"},
{"id":85,"fix":""},
{"id":86,"fix":"Kevin Eubanks"},
{"id":87,"fix":""},
{"id":88,"fix":"Lionel Newman"},
{"id":89,"fix":""},
{"id":90,"fix":"Antonio Carlos Jobim"},
{"id":91,"fix":""},
{"id":92,"fix":""},
{"id":93,"fix":""},
{"id":94,"fix":"Gerry Mulligan"},
{"id":95,"fix":""},
{"id":96,"fix":""}]
