{"id":0,"fix":""},
{"id":1,"fix":""},
{"id":2,"fix":"Johnny Coles"},
{"id":3,"fix":""},
{"id":4,"fix":""},
{"id":5,"fix":""},
{"id":6,"fix":""},
{"id":7,"fix":"Irving Kahl"},
{"id":8,"fix":""},
{"id":9,"fix":""},
{"id":10,"fix":"Jack Stick"},
{"id":11,"fix":""},
{"id":12,"fix":""},
{"id":13,"fix":""},
{"id":14,"fix":""},
{"id":15,"fix":"Wayne Shorter"},
{"id":16,"fix":""},
{"id":17,"fix":""},
{"id":18,"fix":""},
{"id":19,"fix":""},
{"id":20,"fix":""},
{"id":21,"fix":""},
{"id":22,"fix":"Lee Morgan"},
{"id":23,"fix":""},
{"id":24,"fix":""},
{"id":25,"fix":""},
{"id":26,"fix":""},
{"id":27,"fix":""},
